-- This file has been generated by notion. Do not edit.
return {
    [0] = {
        ["type"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["type"] = "WGroupWS",
                ["hidden"] = true,
                ["geom"] = {
                    ["h"] = 768.0,
                    ["w"] = 1366.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                },
                ["name"] = "web",
                ["sizepolicy"] = "full",
                ["level"] = 0.0,
                ["initial_outputs"] = {
                },
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["type"] = "WSplitSplit",
                            ["dir"] = "vertical",
                            ["brs"] = 20.0,
                            ["tls"] = 748.0,
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["type"] = "WFrame",
                                    ["mode"] = 1.0,
                                    ["managed"] = {
                                        [1] = {
                                            ["type"] = "WGroupCW",
                                            ["geom"] = {
                                                ["h"] = 721.0,
                                                ["w"] = 1360.0,
                                                ["x"] = 3.0,
                                                ["y"] = 24.0,
                                            },
                                            ["name"] = "WGroupCW<1>",
                                            ["sizepolicy"] = "full",
                                            ["level"] = 0.0,
                                            ["switchto"] = true,
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WClientWin",
                                                    ["checkcode"] = 1.0,
                                                    ["sizepolicy"] = "full",
                                                    ["windowid"] = 16777257.0,
                                                    ["level"] = 0.0,
                                                    ["bottom"] = true,
                                                    ["geom"] = {
                                                        ["h"] = 721.0,
                                                        ["w"] = 1360.0,
                                                        ["x"] = 0.0,
                                                        ["y"] = 0.0,
                                                    },
                                                },
                                            },
                                        },
                                    },
                                    ["name"] = "Framed PHolder Frame",
                                },
                            },
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                        },
                        ["level"] = 0.0,
                        ["geom"] = {
                            ["h"] = 768.0,
                            ["w"] = 1366.0,
                            ["x"] = 0.0,
                            ["y"] = 0.0,
                        },
                        ["name"] = "WTiling",
                    },
                },
            },
            [2] = {
                ["type"] = "WGroupWS",
                ["geom"] = {
                    ["h"] = 768.0,
                    ["w"] = 1366.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                },
                ["switchto"] = true,
                ["name"] = "dev",
                ["sizepolicy"] = "full",
                ["level"] = 0.0,
                ["initial_outputs"] = {
                },
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["type"] = "WSplitSplit",
                            ["dir"] = "vertical",
                            ["brs"] = 20.0,
                            ["tls"] = 748.0,
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["type"] = "WFrame",
                                    ["mode"] = 1.0,
                                    ["managed"] = {
                                        [1] = {
                                            ["type"] = "WGroupCW",
                                            ["hidden"] = true,
                                            ["sizepolicy"] = "full",
                                            ["geom"] = {
                                                ["h"] = 721.0,
                                                ["w"] = 1360.0,
                                                ["x"] = 3.0,
                                                ["y"] = 24.0,
                                            },
                                            ["level"] = 0.0,
                                            ["name"] = "WGroupCW",
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WClientWin",
                                                    ["checkcode"] = 2.0,
                                                    ["sizepolicy"] = "full",
                                                    ["windowid"] = 14680070.0,
                                                    ["level"] = 0.0,
                                                    ["bottom"] = true,
                                                    ["geom"] = {
                                                        ["h"] = 721.0,
                                                        ["w"] = 1360.0,
                                                        ["x"] = 0.0,
                                                        ["y"] = 0.0,
                                                    },
                                                },
                                            },
                                        },
                                        [2] = {
                                            ["type"] = "WGroupCW",
                                            ["geom"] = {
                                                ["h"] = 721.0,
                                                ["w"] = 1360.0,
                                                ["x"] = 3.0,
                                                ["y"] = 24.0,
                                            },
                                            ["name"] = "WGroupCW<2>",
                                            ["sizepolicy"] = "full",
                                            ["level"] = 0.0,
                                            ["switchto"] = true,
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WClientWin",
                                                    ["checkcode"] = 3.0,
                                                    ["sizepolicy"] = "full",
                                                    ["windowid"] = 18874374.0,
                                                    ["level"] = 0.0,
                                                    ["bottom"] = true,
                                                    ["geom"] = {
                                                        ["h"] = 721.0,
                                                        ["w"] = 1360.0,
                                                        ["x"] = 0.0,
                                                        ["y"] = 0.0,
                                                    },
                                                },
                                            },
                                        },
                                    },
                                    ["name"] = "Framed PHolder Frame<2>",
                                },
                            },
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                        },
                        ["level"] = 0.0,
                        ["geom"] = {
                            ["h"] = 768.0,
                            ["w"] = 1366.0,
                            ["x"] = 0.0,
                            ["y"] = 0.0,
                        },
                        ["name"] = "WTiling<1>",
                    },
                },
            },
            [3] = {
                ["type"] = "WGroupWS",
                ["hidden"] = true,
                ["geom"] = {
                    ["h"] = 768.0,
                    ["w"] = 1366.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                },
                ["name"] = "docs",
                ["sizepolicy"] = "full",
                ["level"] = 0.0,
                ["initial_outputs"] = {
                },
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["type"] = "WFrame",
                                ["mode"] = 1.0,
                                ["managed"] = {
                                },
                                ["name"] = "Framed PHolder Frame<1>",
                            },
                        },
                        ["level"] = 0.0,
                        ["geom"] = {
                            ["h"] = 768.0,
                            ["w"] = 1366.0,
                            ["x"] = 0.0,
                            ["y"] = 0.0,
                        },
                        ["name"] = "WTiling<2>",
                    },
                },
            },
            [4] = {
                ["type"] = "WGroupWS",
                ["hidden"] = true,
                ["geom"] = {
                    ["h"] = 768.0,
                    ["w"] = 1366.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                },
                ["name"] = "vid",
                ["sizepolicy"] = "full",
                ["level"] = 0.0,
                ["initial_outputs"] = {
                },
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["type"] = "WFrame",
                                ["mode"] = 1.0,
                                ["managed"] = {
                                },
                                ["name"] = "Tiling Frame<3>",
                            },
                        },
                        ["level"] = 0.0,
                        ["geom"] = {
                            ["h"] = 768.0,
                            ["w"] = 1366.0,
                            ["x"] = 0.0,
                            ["y"] = 0.0,
                        },
                        ["name"] = "WTiling<3>",
                    },
                },
            },
            [5] = {
                ["type"] = "WGroupWS",
                ["hidden"] = true,
                ["geom"] = {
                    ["h"] = 768.0,
                    ["w"] = 1366.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                },
                ["name"] = "gfx",
                ["sizepolicy"] = "full",
                ["level"] = 0.0,
                ["initial_outputs"] = {
                },
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["type"] = "WFrame",
                                ["mode"] = 1.0,
                                ["managed"] = {
                                },
                                ["name"] = "Tiling Frame<4>",
                            },
                        },
                        ["level"] = 0.0,
                        ["geom"] = {
                            ["h"] = 768.0,
                            ["w"] = 1366.0,
                            ["x"] = 0.0,
                            ["y"] = 0.0,
                        },
                        ["name"] = "WTiling<4>",
                    },
                },
            },
            [6] = {
                ["type"] = "WGroupWS",
                ["hidden"] = true,
                ["geom"] = {
                    ["h"] = 768.0,
                    ["w"] = 1366.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                },
                ["name"] = "other",
                ["sizepolicy"] = "full",
                ["level"] = 0.0,
                ["initial_outputs"] = {
                },
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["type"] = "WFrame",
                                ["mode"] = 1.0,
                                ["managed"] = {
                                },
                                ["name"] = "Tiling Frame<5>",
                            },
                        },
                        ["level"] = 0.0,
                        ["geom"] = {
                            ["h"] = 768.0,
                            ["w"] = 1366.0,
                            ["x"] = 0.0,
                            ["y"] = 0.0,
                        },
                        ["name"] = "WTiling<5>",
                    },
                },
            },
        },
        ["name"] = "WScreen",
    },
}

