-- This file has been generated by notion. Do not edit.
return {
    [1] = "workspacelayout:",
    [2] = "workspacename:other",
    [3] = "workspacename:gfx",
    [4] = "workspacename:vid",
    [5] = "workspacename:docs",
    [6] = "workspacename:dev",
    [7] = "framename:web",
}

