#!/usr/bin/sh
# Push complete or new tasks to todoist

# API token
token=a66f5ce177e92b752069509d18a9f62ea31e961e

# Look for changes
cp -f ${HOME}/.local/share/calcurse/todo /tmp/todo_new
diff -u /tmp/todo_original /tmp/todo_new > /tmp/todo_diff
IFS=$'\n' read -r -d '' -a items <<< "$(tail -n +4 /tmp/todo_diff)"

# Generate the post data
add_item() {
	eval tempid="$1"
	eval uuid="$2"
	eval content="$3"
	cat <<EOF
[{
"type": "item_add",
"temp_id": "${tempid}",
"uuid": "${uuid}",
"args": {
	"content": "${content}"
}
}]
EOF
}

item_complete() {
	eval uuid="$1"
	eval id="$2"
	cat <<EOF
[{
"type": "item_complete",
"uuid": "${uuid}",
"args": {
	"id": "${id}"
}
}]
EOF
}

# Push the changes to todoist
for (( i=0; i<"${#items[@]}"; i++ )); do
	item=${items[$i]}
	if [[ "${item::1}" == "+" ]]; then
		uuid=$(uuidgen)
		tempid=$(uuidgen)
		priority=${item:2:1}
		content=$(echo ${item} | grep -oP "(\+\[-?[0-9]\]\s)\K(.*)")
		if [[ "${priority}" == "-" ]];then
			id=$(echo ${item} | grep -oP "\([0-9]+\)" | tr -d '()')
			curl https://api.todoist.com/sync/v8/sync \
			  -d token=${token} \
			  -d commands="$(item_complete \${uuid} \${id})"
		elif [[ "${priority}" == 0 ]]; then
			curl https://api.todoist.com/sync/v8/sync \
			  -d token=${token} \
			  -d commands="$(add_item \${tempid} \${uuid} \${content})"
		elif [[ "${priority}" -ge 4 ]]; then
			curl https://api.todoist.com/sync/v8/sync \
			  -d token=${token} \
			  -d commands="$(add_item \${tempid} \${uuid} \${content})"
		else
			curl https://api.todoist.com/sync/v8/sync \
			  -d token=${token} \
			  -d commands="$(add_item \${tempid} \${uuid} \${content})"
		fi
	fi
done
${HOME}/.config/calcurse/hooks/pre-load
