git_protocol: https
editor: vim
prompt: enabled
pager: less
aliases:
    co: "!gh pr list | peco | awk '{print $1}' | xargs gh pr checkout"
    open: repo view --web
    issues: issue list
    prs: pr list
    isme: issue list -a betoSolares
    prme: pr list -a betoSolares
    iv: "!gh issue list | peco | awk '{print $1}' | xargs gh issue view --web"
    pv: "!gh pr list | peco | awk '{print $1}' | xargs gh pr view --web"
    ni: issue create -w
    np: pr create -w
