git_protocol: https
editor: vim
prompt: enabled
pager: less
aliases:
    open: repo view --web
    ls-issue: issue list
    ls-pr: pr list
    issue-me: issue list -a betoSolares
    pr-me: pr list -a betoSolares
    view-issue: "!gh issue list | peco | awk '{print $1}' | xargs gh issue view --web"
    view-pr: "!gh pr list | peco | awk '{print $1}' | xargs gh pr view --web"
    new-issue: issue create -w
    new-pr: pr create -w
