git_protocol: https
editor: vim
prompt: enabled
pager: less
aliases:
    open: repo view --web
    ls-issue: issue list
    ls-pr: pr list
    issue-me: issue list -a betoSolares
    pr-me: pr list -a betoSolares
    view-issue: "!git-issues"
    view-pr: "!git-prs"
    new-issue: issue create -w
    new-pr: pr create -w
version: "1"
