#!/bin/sh

# Load and merge the resources file
[ -f "$HOME"/.config/X11/xresources ] && xrdb -merge -I"$HOME" "$HOME"/.config/X11/xresources

# Keyboard adjustment
setxkbmap -option caps:swapescape

# Execute wm
exec dbus-launch notion -searchdir "${HOME}"/.config/notion/ -session "${HOME}"/.config/notion/mysession
